/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
"use client";
import { DebugInstanceErrorWrapper, DebugInstance } from "../../../_debug/components";
export default function ServerError(error) {
    return (<DebugInstanceErrorWrapper data-d="1346_527#1346_624" error={error.error} containerStyles={{
        height: "100%"
    }}><DebugInstance debug-id="1346_624" debug-parent="1346_527"><div/></DebugInstance></DebugInstanceErrorWrapper>);
}
