/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import { forwardRef } from "react";
import cx from "classnames";
import { ClientImage as ClutchClientImage } from "../../../../clutch/components/ClutchImage/client";
import ClutchImage from "../../../../clutch/components/ClutchImage";
import ClutchRichText from "../../../../clutch/components/ClutchRichText";
import { serialize, parseSearchParams } from "../../../_debug/helpers";
import { DebugReports, DebugInstanceErrorWrapper, DebugTextEdit } from "../../../_debug/components";
import "./global.css";
import styles from "./styles.module.css";
async function View({
    params,
    searchParams,
    ...props
}, ref) {
    const vars = {};
    const reports = [
        {
            type: 0,
            vars: serialize(vars),
            props: serialize({
                ...props,
                params: await params,
                searchParams: parseSearchParams(await searchParams)
            })
        }
    ];
    return (<DebugReports debug-reports={reports}><DebugInstanceErrorWrapper data-d="1346_527#1346_624"><div data-d="1346_527#1346_624" className={cx(styles.clt_1346_624, "clt_view", "clt_1346_624")}><DebugInstanceErrorWrapper data-d="1346_624#1582_134"><ClutchClientImage><ClutchImage src="/wordpress-logo.svg?fh=7a5f1b1a775539fd7153b19c1edb543b046dd57fb0ca540fa448749fc722d130" alt="cover" className={cx(styles.clt_1582_134, "clt_1582_134")} data-d="1346_624#1582_134"/></ClutchClientImage></DebugInstanceErrorWrapper><DebugInstanceErrorWrapper data-d="1346_624#1357_10"><ClutchRichText tag="h1" className={cx(styles.clt_1357_10, "clt_1357_10")} data-d="1346_624#1357_10">{<DebugTextEdit data-d="1357_10" data-name="text">WordPress</DebugTextEdit>}</ClutchRichText></DebugInstanceErrorWrapper></div></DebugInstanceErrorWrapper></DebugReports>);
}
export default forwardRef(View);
