/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
"use client";
import { DebugInstanceErrorWrapper, DebugInstance } from "../_debug/components";
export default function ServerError(error) {
    return (<DebugInstanceErrorWrapper data-d="1648_16#1648_16" error={error.error} containerStyles={{
        height: "100%"
    }}><DebugInstance debug-id="1648_16"><div/></DebugInstance></DebugInstanceErrorWrapper>);
}
