/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
  
module.exports = {
  transpilePackages: ['@clutch-marketplace/clutch.graphql', '@clutch-marketplace/clutch.video', '@clutch-marketplace/clutch.functions', '@clutch-marketplace/clutch.rest', '@clutch-marketplace/clutch.google-analytics', '@clutch-marketplace/clutch.marketing-templates', '@clutch-marketplace/clutch.google-maps', '@clutch-marketplace/clutch.actions', '@clutch-marketplace/clutch.wordpress', '@clutch-marketplace/clutch.lightbox', '@clutch-marketplace/clutch.clutch-elements'],
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '*',
      },
      {
        protocol: 'http',
        hostname: '*',
      },
      {
        hostname: 'localhost',
      },
      {
        hostname: '**.local',
      }
    ],
  },
  experimental: {
    turbo: {
      rules: {
        '*.svg': {
          loaders: [require.resolve('./clutch-svg-loader.js')],
          as: '*.js',
        },
      },
    },
  },
  devIndicators: false,
};