/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
'use client';

import { useState, useMemo } from 'react';

export default function NotFoundRedirect({children}) {
  const [loading, setLoading] = useState(true);
  const pathname =
    typeof window !== 'undefined' && window.location.pathname !== 'not-found';

  useMemo(() => {
    if (pathname) {
      fetch(window.location.href)
        .then((response) => {
          if (response.ok) {
            window.location.reload();
          } else {
            setLoading(false);
          }
        })
        .catch(() => {
          setLoading(false);
        });
    }
  }, [pathname, setLoading]);

  return loading ? null : <>{children}</>;
}