/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
'use client';

import { useState, useMemo } from 'react';
import fontsClassName from '../fonts';
import '../variables.css';
import '../global.css';
import '../classes.css';

export default function NotFound() {
  const [loading, setLoading] = useState(true);
  const pathname =
    typeof window !== 'undefined' && window.location.pathname !== 'not-found';

  useMemo(() => {
    if (pathname) {
      const maxRetries = 3;
      const delay = 1000;

      const fetchData = (attempt = 1) => {
        fetch(window.location.href)
          .then((response) => {
            if (response.ok) {
              window.location.reload();
            } else {
              if (attempt < maxRetries) {
                setTimeout(() => fetchData(attempt + 1), delay);
              } else {
                setLoading(false);
              }
            }
          })
          .catch(() => {
            if (attempt < maxRetries) {
              setTimeout(() => fetchData(attempt + 1), delay);
            } else {
              setLoading(false);
            }
          });
      };

      fetchData();
    }
  }, [pathname, setLoading]);

  return (
    <html lang="en" className={fontsClassName}>
      <body>
        {loading ? null : (
          <div>
            <h2>Page not found</h2>
            <p>The requested page could not be found.</p>
            <p>Make sure this page exists in Clutch and is properly linked.</p>
            <p>
              If you want to customize this 404 page, create a new page with path{' '}
              <code>not-found</code> under the desired Layout.
            </p>
          </div>
      )}
      </body>
    </html>
  );
}