/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
"use client";
import { DebugInstanceErrorWrapper, DebugInstance } from "../../../_debug/components";
export default function ServerError(error) {
    return (<DebugInstanceErrorWrapper data-d="1648_34#1654_15" error={error.error} containerStyles={{
        height: "100%"
    }}><DebugInstance debug-id="1654_15" debug-parent="1648_34"><div/></DebugInstance></DebugInstanceErrorWrapper>);
}
