/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
"use client";
import { DebugInstanceErrorWrapper, DebugInstance } from "../../_debug/components";
export default function ServerError(error) {
    return (<DebugInstanceErrorWrapper data-d="1_405#1_405" error={error.error} containerStyles={{
        height: "100%"
    }}><DebugInstance debug-id="1_405"><div/></DebugInstance></DebugInstanceErrorWrapper>);
}
