/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import { NextRequest, NextFetchEvent } from "next/server";
import { middlewarePipe } from "./clutch/helpers/middleware-pipe";
const cltPluginsHooks = [].filter(Boolean);
export async function middleware(request: NextRequest, event: NextFetchEvent) {
    return middlewarePipe(cltPluginsHooks, request, event);
}
