/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import { createPost } from "@clutch-marketplace/clutch.wordpress/dist/actions/actions.js";
import { createPost as createPost1 } from "@clutch-marketplace/clutch.wordpress/dist/actions/posts.js";
import { search } from "@clutch-marketplace/clutch.wordpress/dist/queries/search.js";
import { getPosts, getPostBySlug, getPostById } from "@clutch-marketplace/clutch.wordpress/dist/queries/posts.js";
import { getPages, getPageBySlug, getPageById, getFrontPage } from "@clutch-marketplace/clutch.wordpress/dist/queries/pages.js";
import { getUsers, getUserBySlug, getUserById } from "@clutch-marketplace/clutch.wordpress/dist/queries/users.js";
import { getTaxonomyTerms, getTaxonomyTermBySlug, getTaxonomyTermById } from "@clutch-marketplace/clutch.wordpress/dist/queries/taxonomies.js";
import { getMenu } from "@clutch-marketplace/clutch.wordpress/dist/queries/menus.js";
import { getMedia, getMediaItemBySlug, getMediaItemById } from "@clutch-marketplace/clutch.wordpress/dist/queries/media.js";
import { REST } from "@clutch-marketplace/clutch.rest/dist/actions/REST.js";
import { REST as REST1 } from "@clutch-marketplace/clutch.rest/dist/queries/REST.js";
import { GraphQL } from "@clutch-marketplace/clutch.graphql/dist/actions/GraphQL.js";
import { GraphQL as GraphQL1 } from "@clutch-marketplace/clutch.graphql/dist/queries/GraphQL.js";
import { navigate, goBack, goForward, refresh, replace } from "@clutch-marketplace/clutch.actions/dist/actions/navigation.js";
import { sendGoogleTagManagerEvent, sendGoogleAnalyticsEvent } from "@clutch-marketplace/clutch.google-analytics/dist/actions/google.js";
import { getDummyPosts } from "@clutch-marketplace/clutch.functions/dist/queries/queries.js";
export const serverFunctions = {
    "@clutch-marketplace/clutch.rest": {
        "/dist/actions/REST.ts": {
            "REST": REST
        },
        "/dist/queries/REST.ts": {
            "REST": REST1
        }
    },
    "@clutch-marketplace/clutch.wordpress": {
        "/dist/actions/actions.ts": {
            "createPost": createPost
        },
        "/dist/actions/posts.ts": {
            "createPost": createPost1
        },
        "/dist/queries/search.ts": {
            "search": search
        },
        "/dist/queries/posts.ts": {
            "getPosts": getPosts,
            "getPostBySlug": getPostBySlug,
            "getPostById": getPostById
        },
        "/dist/queries/pages.ts": {
            "getPages": getPages,
            "getPageBySlug": getPageBySlug,
            "getPageById": getPageById,
            "getFrontPage": getFrontPage
        },
        "/dist/queries/users.ts": {
            "getUsers": getUsers,
            "getUserBySlug": getUserBySlug,
            "getUserById": getUserById
        },
        "/dist/queries/taxonomies.ts": {
            "getTaxonomyTerms": getTaxonomyTerms,
            "getTaxonomyTermBySlug": getTaxonomyTermBySlug,
            "getTaxonomyTermById": getTaxonomyTermById
        },
        "/dist/queries/menus.ts": {
            "getMenu": getMenu
        },
        "/dist/queries/media.ts": {
            "getMedia": getMedia,
            "getMediaItemBySlug": getMediaItemBySlug,
            "getMediaItemById": getMediaItemById
        }
    },
    "@clutch-marketplace/clutch.actions": {
        "/dist/actions/navigation.ts": {
            "navigate": navigate,
            "goBack": goBack,
            "goForward": goForward,
            "refresh": refresh,
            "replace": replace
        }
    },
    "@clutch-marketplace/clutch.graphql": {
        "/dist/actions/GraphQL.ts": {
            "GraphQL": GraphQL
        },
        "/dist/queries/GraphQL.ts": {
            "GraphQL": GraphQL1
        }
    },
    "@clutch-marketplace/clutch.google-analytics": {
        "/dist/actions/google.ts": {
            "sendGoogleTagManagerEvent": sendGoogleTagManagerEvent,
            "sendGoogleAnalyticsEvent": sendGoogleAnalyticsEvent
        }
    },
    "@clutch-marketplace/clutch.functions": {
        "/dist/queries/queries.ts": {
            "getDummyPosts": getDummyPosts
        }
    }
};
